### PR TITLE
Add a todo list for CIV

### PR DESCRIPTION
**Pull request by jibanCat**
I added some descriptions for the redshift code since most of the files might not be useful for CIV detections.

My suggestion is to work out the voigt.c first for CIV profile,
and then test this profile if it is working fine on detecting some selected CIV spectra.

### CODE REVIEW

**Comment by jibanCat** [comment]
I did not notice this hasn't merged so I pushed again.

This time with a read_spec for DR7 but in python.

Need a MATLAB version, maybe in another PR.

**Comment by jibanCat** [comment]
Merge 😃

**Comment by rezamonadi** [comment]
sdss_dr7 python code!

**Comment by rezamonadi** [comment]
Merged...

**Pull request merged**
