### PR TITLE
Remove off-end model fitting and prepare train_ind

### PR DESCRIPTION
**Pull request by jibanCat**
Remove the off-end model fitting (fitting i.i.d Gaussians to red and blue ends outside of the model window) since we only care region within the model window for CIV project.

### CODE REVIEW

**Comment by jibanCat** [comment]
I think this one can be merged unless there are any unexpected bugs.

Then we can move on to work with train_ind (building a variable in catalog.mat for flagging CIV spectra)

**Comment by rezamonadi** [comment]
Sorry I didn’t looked at that. You for sure know better. So go ahead and merge! 

-Reza

**Comment by jibanCat** [comment]
Sorry I was going to merge actually lol

Thanks for merging it!

**Comment by rezamonadi** [comment]
🐸






----------------------------------
Reza Monadi
Ph.D. Student
Department of Physics and Astronomy
University of California, Riverside
Webpage: https://rezamonadi.github.io/
-----------------------------------

**Pull request merged**
